apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: store-prod
spec:
  generators:
    - git:
        repoURL: https://github.com/ame-digitals/manifests.git
        revision: main
        directories:
          - path: apps/*/overlays/prod
  template:
    metadata:
      name: "{{path[1]}}-prod"
    spec:
      project: amed
      source:
        repoURL: https://github.com/ame-digitals/manifests.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "amedp-{{path[0]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: store-test
spec:
  generators:
    - git:
        repoURL: https://github.com/ame-digitals/manifests.git
        revision: main
        directories:
          - path: apps/*/overlays/test
  template:
    metadata:
      name: "{{path[1]}}-test"
    spec:
      project: amed
      source:
        repoURL: https://github.com/ame-digitals/manifests.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "amedt-{{path[0]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
