apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  storage:
    size: 5Gi
  enableSuperuserAccess: true
  env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: WHEN_REQUIRED
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: WHEN_REQUIRED
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
    limits:
      memory: "50Mi"
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 3GB
  managed:
    roles:
      - name: store-user
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: store-db-credentials
